### ISSUE TITLE
Floats or doubles ?

### ISSUE THREAD

**Issue by gihanmudalige** [UK-MAC/CloverLeaf_ref#1]
Should not these constants be suffixed by _8 ?

https://github.com/Warwick-PCAV/CloverLeaf_ref/blob/master/read_input.f90#L61

Probably would not make much difference. But I did find minor variations when comparing OPS CLoverleaf with the reference implementation.

**Comment by davidbeckingsale** [comment]
Yes - for the sake of completeness I think that's a good idea.
I'll check this with @waynegaudin and update if necessary.

**Comment by gihanmudalige** [comment]
This was quite a minor issue .. but it did put me off finding the real issue for some time

**Comment by davidbeckingsale** [comment]
Sorry to hear that - I've had a few of those whilst working with the AMR version of CloverLeaf.
If something like this comes up again, please don't hesitate to email us straight away.
