### ISSUE TITLE
3D - update_halo inconsistencies

### ISSUE THREAD

**Issue by reguly** [UK-MAC/CloverLeaf_ref#2]
in the 3d version of update_halo there seem to be some inconsistencies when updating variables, specifically:
vol_flux_x Front
mass_flux_x Front
mass_flux_z Right
The stencils do not seem to match all the others - is this intentional?

**Comment by waynegaudin** [comment]
You may have found the big I have been looking for!

I am back in the office in Thursday. I'll have a proper look then.

Ta

Wayne

**Comment by reguly** [comment]
I think there may be a couple more issues with loop bounds too:
mass_flux_z bottom seems inconsistent with top
perhaps in other update loops too, where size of the array is *_min-2 -> *_max+3 but the loop is only *_max+2

**Comment by waynegaudin** [comment]
Im sure there are some other issues because I don't get the symmetry I
expect.

I'll check out these issues and fully test on Thursday.

Let me know if you spot anything else.

Thanks

Wayne
